### ISSUE TITLE
Support for Laravel 6

### ISSUE THREAD

**Issue by thoss** [sebbmeyer/laravel-teams-connector#7] opened 2019-10-08 11:03 UTC
Is it possible to add support for Laravel 6?

Thanks in advance.

**Comment by devinhyden** [comment] 2019-10-09 21:16
I created a PR #8 for Laravel 6 and confirmed it is working on my local install. Hopefully it will be merged soon.

**Comment by sebbmeyer** [comment] 2019-10-10 09:05
@SirPoot- I will check the PR as soon as I can. Since you added more than just the support for Laravel 6 I can't just accept it. I should be probably be able to do it later today

**Comment by devinhyden** [comment] 2019-10-10 13:04
@sebbmeyer I should have submitted two PRs. Let me know if you would like me to split them up.

**Comment by sebbmeyer** [comment] 2019-10-11 09:16
@SirPoot- It's ok, since I dropped the support of PHP 5.x and old versions of Laravel

**Closed as completed by sebbmeyer** 2019-10-11 09:16 UTC
